# Site settings
title: Dominic's Desk -
subtitle: Projects and studying
email: youremailaddress@gmail.com
description: A website about me and all my personal projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Dominic Schroeder
street_address: Ohlenstedter Str. 26
city: Hambergen
state:
zip_code: 27729
country: Germany
phone: (04793) 4324566

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
